# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:
    env:
      WANNAJOIN_DB_NAME: ${{ secrets.WANNAJOIN_DB_NAME }}
      WANNAJOIN_DB_PORT: ${{ secrets.WANNAJOIN_DB_PORT }}
      WANNAJOIN_DB_PW: ${{ secrets.WANNAJOIN_DB_PW }}
      WANNAJOIN_DB_SERVER: ${{ secrets.WANNAJOIN_DB_SERVER }}
      WANNAJOIN_DB_URL: ${{ secrets.WANNAJOIN_DB_URL }}
      WANNAJOIN_DB_USER: ${{ secrets.WANNAJOIN_DB_USER }}

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Compile
        run: mvn clean compile -T 1C

      - name: Test
        run: mvn test -T 1C

      - name: Package
        run: mvn package -T 1C

      - name: Upload test artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./DBConnectionTestLogs.txt

      - name: Config user
        run: git config --global user.name "spiralspree" && git config --global user.email "spiralspree@gmail.com"

      - name: Create pull request to master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr create --base master --head development --fill

      - name: Merge pull request to master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr merge -r --admin
